name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: Dependencies
        run: yarn install
      - name: Verification
        run: yarn test
      - name: Deployment
        run: yarn deploy
